# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "be_taskable"
  s.version = "0.6.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sebastian Porto"]
  s.date = "2013-12-18"
  s.description = "BeTaskable is a small framework for creating and maintaining tasks / chores / assignments. Meaning something that someone has to do."
  s.email = "sebasporto@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "Rakefile",
    "VERSION",
    "be_taskable.gemspec",
    "docs/task_refresh_activity_diagram.delineato",
    "docs/taskable_complete_flow.delineato",
    "lib/be_taskable.rb",
    "lib/be_taskable/task.rb",
    "lib/be_taskable/task_assignment.rb",
    "lib/be_taskable/task_resolver.rb",
    "lib/be_taskable/task_runner.rb",
    "lib/be_taskable/taskable.rb",
    "lib/be_taskable/tasker.rb",
    "lib/generators/be_taskable/migration_generator.rb",
    "lib/generators/be_taskable/resolver_generator.rb",
    "lib/generators/be_taskable/templates/active_record/migration.rb",
    "lib/generators/be_taskable/templates/resolver.rb.tpl",
    "readme.md",
    "spec/be_taskable/integration/end_to_end_spec.rb",
    "spec/be_taskable/integration/irrelevance_spec.rb",
    "spec/be_taskable/unit/be_taskable_spec.rb",
    "spec/be_taskable/unit/task_assignment_spec.rb",
    "spec/be_taskable/unit/task_runner_spec.rb",
    "spec/be_taskable/unit/task_spec.rb",
    "spec/be_taskable/unit/taskable_spec.rb",
    "spec/be_taskable/unit/tasker_spec.rb",
    "spec/database.yml",
    "spec/models.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/sporto/be_taskable"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Mini framework for creating and maintaining user tasks"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 4.0"])
      s.add_runtime_dependency(%q<state_machine>, ["~> 1.1"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, ["~> 2.14"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_development_dependency(%q<database_cleaner>, ["~> 1.1"])
    else
      s.add_dependency(%q<rails>, ["~> 4.0"])
      s.add_dependency(%q<state_machine>, ["~> 1.1"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, ["~> 2.14"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, ["~> 3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.2"])
      s.add_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_dependency(%q<database_cleaner>, ["~> 1.1"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 4.0"])
    s.add_dependency(%q<state_machine>, ["~> 1.1"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, ["~> 2.14"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, ["~> 3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.2"])
    s.add_dependency(%q<jeweler>, ["~> 1.8"])
    s.add_dependency(%q<database_cleaner>, ["~> 1.1"])
  end
end

